#!/bin/bash
#
# Hook built by extending git's pre-commit example hook

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

function run() {
  echo $@
  $@
}

# Check that code compiles and is warnings free
stack build || exit $?
# Check that tests pass FIXME REENABLE me
# stack test || exit $?
# Check that hints are applied
stack exec hlint . || exit $?
# Generate documentation from sources
stack exec haddock -- --html $(find src -name \*.hs) -o html || exit $?

echo "Testing --print"
# Check that zzbot --print succeeds on some configurations:
for CONFIG in config.xml examples/kcg.xml
do
  run stack exec zzbot -- --print configs/$CONFIG || exit $?
done

# Check that zzbot fails on some configurations:
echo "Testing executing failing configurations"
FAILURE_CONFIGS="tests/haltOnFailure1.xml"
for CONFIG in $FAILURE_CONFIGS
do
  run stack exec zzbot -- configs/$CONFIG
  [[ "$?" != "0" ]] || exit $?
done

# Check that zzbot succeeds on some configurations:
echo "Testing executing successful configurations"
SUCCESS_CONFIGS="config.xml tests/db1.xml tests/db_nonull.xml tests/haltOnFailure2.xml tests/haltOnFailure3.xml"
for CONFIG in $SUCCESS_CONFIGS
do
  run stack exec zzbot -- configs/$CONFIG || exit $?
done
